export const LOGIN = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAILED';
export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const USERINFO = 'USERINFO';
export const USERINFO_SUCCSS = 'USERINFO_SUCCSS';
export const USERINFO_FAIL = 'USERINFO_FAIL';
export const PASSWORD = 'PASSWORD_REQUEST';
export const PASSWORD_SUCCESS = 'PASSWORD_SUCCESS';
export const PASSWORD_FAIL = 'PASSWORD_FAILED';
export const PASSWORD_CHANGE = 'PASSWORD_CHANGE_REQUEST';
export const PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS';
export const PASSWORD_CHANGE_FAIL = 'PASSWORD_CHANGE_FAILED';

