export const AFFILIATES = 'AFFILIATES';
export const AFFILIATES_SUCCESS = 'AFFILIATES_SUCCESS';
export const AFFILIATES_FAIL = 'AFFILIATES_FAIL';
export const AFFILIATES_CLEAR = 'AFFILIATES_CLEAR';

export const AFFILIATE_LOAD = 'AFFILIATE_LOAD';
export const AFFILIATE_LOAD_SUCCESS = 'AFFILIATE_LOAD_SUCCESS';
export const AFFILIATE_LOAD_FAIL = 'AFFILIATE_LOAD_FAIL';
export const AFFILIATE_CLEAR = 'AFFILIATE_CLEAR';

export const AFFILIATE_CREATE = 'AFFILIATE_CREATE';
export const AFFILIATE_CREATE_SUCCESS = 'AFFILIATE_CREATE_SUCCESS';
export const AFFILIATE_CREATE_FAIL = 'AFFILIATE_CREATE_FAIL';

export const AFFILIATE_EDIT = 'AFFILIATE_EDIT';
export const AFFILIATE_EDIT_SUCCESS = 'AFFILIATE_EDIT_SUCCESS';
export const AFFILIATE_EDIT_FAIL = 'AFFILIATE_EDIT_FAIL';

export const AFFILIATE_UPDATE = 'AFFILIATE_UPDATE';
export const AFFILIATE_UPDATE_SUCCESS = 'AFFILIATE_UPDATE_SUCCESS';
export const AFFILIATE_UPDATE_FAIL = 'AFFILIATE_UPDATE_FAIL';

export const AFFILIATE_DELETE = 'AFFILIATE_DELETE';
export const AFFILIATE_DELETE_SUCCESS = 'AFFILIATE_DELETE_SUCCESS';
export const AFFILIATE_DELETE_FAIL = 'AFFILIATE_DELETE_FAIL';

export const AFFILIATE_CLEAR_NETWORK_STATE = 'AFFILIATE_CLEAR_NETWORK_STATE';
