export const CATEGORIES = 'USERS';
export const CATEGORIES_SUCCESS = 'CATEGORIES_SUCCESS';
export const CATEGORIES_FAIL = 'CATEGORIES_FAIL';
export const CATEGORIES_CLEAR = 'CATEGORIES_CLEAR';

export const CATEGORY_LOAD = 'CATEGORY_LOAD';
export const CATEGORY_LOAD_SUCCESS = 'CATEGORY_LOAD_SUCCESS';
export const CATEGORY_LOAD_FAIL = 'CATEGORY_LOAD_FAIL';
export const CATEGORY_CLEAR = 'CATEGORY_CLEAR';

export const CATEGORY_CREATE = 'CATEGORY_CREATE';
export const CATEGORY_CREATE_SUCCESS = 'CATEGORY_CREATE_SUCCESS';
export const CATEGORY_CREATE_FAIL = 'CATEGORY_CREATE_FAIL';

export const CATEGORY_EDIT = 'CATEGORY_EDIT';
export const CATEGORY_EDIT_SUCCESS = 'CATEGORY_EDIT_SUCCESS';
export const CATEGORY_EDIT_FAIL = 'CATEGORY_EDIT_FAIL';

export const CATEGORY_UPDATE = 'CATEGORY_UPDATE';
export const CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS';
export const CATEGORY_UPDATE_FAIL = 'CATEGORY_UPDATE_FAIL';

export const CATEGORY_DELETE = 'CATEGORY_DELETE';
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS';
export const CATEGORY_DELETE_FAIL = 'CATEGORY_DELETE_FAIL';

export const CATEGORY_CLEAR_NETWORK_STATE = 'CATEGORY_CLEAR_NETWORK_STATE';
