export const ADMIN_AFFLI_SITES = 'ADMIN_AFFLI_SITES';
export const ADMIN_AFFLI_SITES_SUCCESS = 'ADMIN_AFFLI_SITESL_SUCCESS';
export const ADMIN_AFFLI_SITES_FAIL = 'ADMIN_AFFLI_SITES_FAIL';
export const ADMIN_AFFLI_SITES_CLEAR = 'ADMIN_AFFLI_SITES_CLEAR';

export const ADMIN_AFFLI_SITES_ALL = 'ADMIN_AFFLI_SITES_ALL';
export const ADMIN_AFFLI_SITES_ALL_SUCCESS = 'ADMIN_AFFLI_SITES_ALL_SUCCESS';
export const ADMIN_AFFLI_SITES_ALL_FAIL = 'ADMIN_AFFLI_SITES_ALL_FAIL';
export const ADMIN_AFFLI_SITES_ALL_CLEAR = 'ADMIN_AFFLI_SITES_ALL_CLEAR';

export const ADMIN_AFFL_SITE_LOAD = 'ROLADMIN_AFFL_SITE_LOADE_LOAD';
export const ADMIN_AFFL_SITE_LOAD_SUCCESS = 'ADMIN_AFFL_SITE_LOAD_SUCCESS';
export const ADMIN_AFFL_SITE_LOAD_FAIL = 'ADMIN_AFFL_SITE_LOAD_FAIL';
export const ADMIN_AFFL_SITE_CLEAR = 'ADMIN_AFFL_SITE_CLEAR';

export const ADMIN_AFFL_SITE_CREATE = 'ADMIN_AFFL_SITE_CREATE';
export const ADMIN_AFFL_SITE_CREATE_SUCCESS = 'ADMIN_AFFL_SITE_CREATE_SUCCESS';
export const ADMIN_AFFL_SITE_CREATE_FAIL = 'ADMIN_AFFL_SITE_CREATE_FAIL';

export const ADMIN_AFFL_SITE_EDIT = 'ADMIN_AFFL_SITE_EDIT';
export const ADMIN_AFFL_SITE_EDIT_SUCCESS = 'ADMIN_AFFL_SITE_EDIT_SUCCESS';
export const ADMIN_AFFL_SITE_EDIT_FAIL = 'ADMIN_AFFL_SITE_EDIT_FAIL';

export const ADMIN_AFFL_SITE_UPDATE = 'ADMIN_AFFL_SITE_UPDATE';
export const ADMIN_AFFL_SITE_UPDATE_SUCCESS = 'ADMIN_AFFL_SITE_UPDATE_SUCCESS';
export const ADMIN_AFFL_SITE_UPDATE_FAIL = 'ADMIN_AFFL_SITE_UPDATE_FAIL';

export const ADMIN_AFFL_SITE_DELETE = 'ADMIN_AFFL_SITE_DELETE';
export const ADMIN_AFFL_SITE_DELETE_SUCCESS = 'ADMIN_AFFL_SITE_DELETE_SUCCESS';
export const ADMIN_AFFL_SITE_DELETE_FAIL = 'ADMIN_AFFL_SITE_DELETE_FAIL';

export const ADMIN_AFFL_SITE_CLEAR_NETWORK_STATE = 'ADMIN_AFFL_SITE_CLEAR_NETWORK_STATE';
