export const ADMIN_ACL_ROLES = 'ADMIN_ACL_ROLES';
export const ADMIN_ACL_ROLES_SUCCESS = 'ADMIN_ACL_ROLESL_SUCCESS';
export const ADMIN_ACL_ROLES_FAIL = 'ADMIN_ACL_ROLES_FAIL';
export const ADMIN_ACL_ROLES_CLEAR = 'ADMIN_ACL_ROLES_CLEAR';

export const ADMIN_ACL_ROLES_ALL = 'ADMIN_ACL_ROLES_ALL';
export const ADMIN_ACL_ROLES_ALL_SUCCESS = 'ADMIN_ACL_ROLES_ALL_SUCCESS';
export const ADMIN_ACL_ROLES_ALL_FAIL = 'ADMIN_ACL_ROLES_ALL_FAIL';
export const ADMIN_ACL_ROLES_ALL_CLEAR = 'ADMIN_ACL_ROLES_ALL_CLEAR';

export const ADMIN_ACL_ROLE_LOAD = 'ROLADMIN_ACL_ROLE_LOADE_LOAD';
export const ADMIN_ACL_ROLE_LOAD_SUCCESS = 'ADMIN_ACL_ROLE_LOAD_SUCCESS';
export const ADMIN_ACL_ROLE_LOAD_FAIL = 'ADMIN_ACL_ROLE_LOAD_FAIL';
export const ADMIN_ACL_ROLE_CLEAR = 'ADMIN_ACL_ROLE_CLEAR';

export const ADMIN_ACL_ROLE_CREATE = 'ADMIN_ACL_ROLE_CREATE';
export const ADMIN_ACL_ROLE_CREATE_SUCCESS = 'ADMIN_ACL_ROLE_CREATE_SUCCESS';
export const ADMIN_ACL_ROLE_CREATE_FAIL = 'ADMIN_ACL_ROLE_CREATE_FAIL';

export const ADMIN_ACL_ROLE_EDIT = 'ADMIN_ACL_ROLE_EDIT';
export const ADMIN_ACL_ROLE_EDIT_SUCCESS = 'ADMIN_ACL_ROLE_EDIT_SUCCESS';
export const ADMIN_ACL_ROLE_EDIT_FAIL = 'ADMIN_ACL_ROLE_EDIT_FAIL';

export const ADMIN_ACL_ROLE_UPDATE = 'ADMIN_ACL_ROLE_UPDATE';
export const ADMIN_ACL_ROLE_UPDATE_SUCCESS = 'ADMIN_ACL_ROLE_UPDATE_SUCCESS';
export const ADMIN_ACL_ROLE_UPDATE_FAIL = 'ADMIN_ACL_ROLE_UPDATE_FAIL';

export const ADMIN_ACL_ROLE_DELETE = 'ADMIN_ACL_ROLE_DELETE';
export const ADMIN_ACL_ROLE_DELETE_SUCCESS = 'ADMIN_ACL_ROLE_DELETE_SUCCESS';
export const ADMIN_ACL_ROLE_DELETE_FAIL = 'ADMIN_ACL_ROLE_DELETE_FAIL';

export const ADMIN_ACL_ROLE_CLEAR_NETWORK_STATE = 'ADMIN_ACL_ROLE_CLEAR_NETWORK_STATE';
