export const ADMIN_AFFLI_CATEGORIES = 'ADMIN_AFFLI_CATEGORIES';
export const ADMIN_AFFLI_CATEGORIES_SUCCESS = 'ADMIN_AFFLI_CATEGORIESL_SUCCESS';
export const ADMIN_AFFLI_CATEGORIES_FAIL = 'ADMIN_AFFLI_CATEGORIES_FAIL';
export const ADMIN_AFFLI_CATEGORIES_CLEAR = 'ADMIN_AFFLI_CATEGORIES_CLEAR';

export const ADMIN_AFFLI_CATEGORIES_ALL = 'ADMIN_AFFLI_CATEGORIES_ALL';
export const ADMIN_AFFLI_CATEGORIES_ALL_SUCCESS = 'ADMIN_AFFLI_CATEGORIES_ALL_SUCCESS';
export const ADMIN_AFFLI_CATEGORIES_ALL_FAIL = 'ADMIN_AFFLI_CATEGORIES_ALL_FAIL';
export const ADMIN_AFFLI_CATEGORIES_ALL_CLEAR = 'ADMIN_AFFLI_CATEGORIES_ALL_CLEAR';

export const ADMIN_AFFL_CATEGORY_LOAD = 'ROLADMIN_AFFL_CATEGORY_LOADE_LOAD';
export const ADMIN_AFFL_CATEGORY_LOAD_SUCCESS = 'ADMIN_AFFL_CATEGORY_LOAD_SUCCESS';
export const ADMIN_AFFL_CATEGORY_LOAD_FAIL = 'ADMIN_AFFL_CATEGORY_LOAD_FAIL';
export const ADMIN_AFFL_CATEGORY_CLEAR = 'ADMIN_AFFL_CATEGORY_CLEAR';

export const ADMIN_AFFL_CATEGORY_CREATE = 'ADMIN_AFFL_CATEGORY_CREATE';
export const ADMIN_AFFL_CATEGORY_CREATE_SUCCESS = 'ADMIN_AFFL_CATEGORY_CREATE_SUCCESS';
export const ADMIN_AFFL_CATEGORY_CREATE_FAIL = 'ADMIN_AFFL_CATEGORY_CREATE_FAIL';

export const ADMIN_AFFL_CATEGORY_EDIT = 'ADMIN_AFFL_CATEGORY_EDIT';
export const ADMIN_AFFL_CATEGORY_EDIT_SUCCESS = 'ADMIN_AFFL_CATEGORY_EDIT_SUCCESS';
export const ADMIN_AFFL_CATEGORY_EDIT_FAIL = 'ADMIN_AFFL_CATEGORY_EDIT_FAIL';

export const ADMIN_AFFL_CATEGORY_UPDATE = 'ADMIN_AFFL_CATEGORY_UPDATE';
export const ADMIN_AFFL_CATEGORY_UPDATE_SUCCESS = 'ADMIN_AFFL_CATEGORY_UPDATE_SUCCESS';
export const ADMIN_AFFL_CATEGORY_UPDATE_FAIL = 'ADMIN_AFFL_CATEGORY_UPDATE_FAIL';

export const ADMIN_AFFL_CATEGORY_DELETE = 'ADMIN_AFFL_CATEGORY_DELETE';
export const ADMIN_AFFL_CATEGORY_DELETE_SUCCESS = 'ADMIN_AFFL_CATEGORY_DELETE_SUCCESS';
export const ADMIN_AFFL_CATEGORY_DELETE_FAIL = 'ADMIN_AFFL_CATEGORY_DELETE_FAIL';

export const ADMIN_AFFL_CATEGORY_CLEAR_NETWORK_STATE = 'ADMIN_AFFL_CATEGORY_CLEAR_NETWORK_STATE';
