export const STORE_LIST = 'STORE_LIST';
export const STORE_LIST_SUCCESS = 'STORE_LIST_SUCCESS';
export const STORE_LIST_FAIL = 'STORE_LIST_FAIL';
export const STORE_LIST_CLEAR = 'STORE_LIST_CLEAR';

export const STORE_LIST_ALL = 'STORE_LIST_ALL';
export const STORE_LIST_ALL_SUCCESS = 'STORE_LIST_ALL_SUCCESS';
export const STORE_LIST_ALL_FAIL = 'STORE_LIST_ALL_FAIL';
export const STORE_LIST_ALL_CLEAR = 'STORE_LIST_ALL_CLEAR';

export const STORE_ITEM_LOAD = 'STORE_ITEM_LOAD';
export const STORE_ITEM_LOAD_SUCCESS = 'STORE_ITEM_LOAD_SUCCESS';
export const STORE_ITEM_LOAD_FAIL = 'STORE_ITEM_LOAD_FAIL';
export const STORE_ITEM_CLEAR = 'STORE_ITEM_CLEAR';

export const STORE_ITEM_CREATE = 'STORE_ITEM_CREATE';
export const STORE_ITEM_CREATE_SUCCESS = 'STORE_ITEM_CREATE_SUCCESS';
export const STORE_ITEM_CREATE_FAIL = 'STORE_ITEM_CREATE_FAIL';

export const STORE_ITEM_EDIT = 'STORE_ITEM_EDIT';
export const STORE_ITEM_EDIT_SUCCESS = 'STORE_ITEM_EDIT_SUCCESS';
export const STORE_ITEM_EDIT_FAIL = 'STORE_ITEM_EDIT_FAIL';

export const STORE_ITEM_UPDATE = 'STORE_ITEM_UPDATE';
export const STORE_ITEM_UPDATE_SUCCESS = 'STORE_ITEM_UPDATE_SUCCESS';
export const STORE_ITEM_UPDATE_FAIL = 'STORE_ITEM_UPDATE_FAIL';

export const STORE_ITEM_DELETE = 'STORE_ITEM_DELETE';
export const STORE_ITEM_DELETE_SUCCESS = 'STORE_ITEM_DELETE_SUCCESS';
export const STORE_ITEM_DELETE_FAIL = 'STORE_ITEM_DELETE_FAIL';

export const STORE_ITEM_CLEAR_NETWORK_STATE = 'STORE_ITEM_CLEAR_NETWORK_STATE';
