export const ACL_ROUTES = 'ACL_ROUTES';
export const ACL_ROUTES_SUCCESS = 'ACL_ROUTES_SUCCESS';
export const ACL_ROUTES_FAIL = 'ACL_ROUTES_FAIL';
export const ACL_ROUTES_CLEAR = 'ACL_ROUTES_CLEAR';

export const ACL_ROUTES_ALL = 'ACL_ROUTES_ALL';
export const ACL_ROUTES_ALL_SUCCESS = 'ACL_ROUTES_ALL_SUCCESS';
export const ACL_ROUTES_ALL_FAIL = 'ACL_ROUTES_ALL_FAIL';
export const ACL_ROUTES_ALL_CLEAR = 'ACL_ROUTES_ALL_CLEAR';

export const ACL_ROUTE_LOAD = 'ACL_ROUTE_LOAD';
export const ACL_ROUTE_LOAD_SUCCESS = 'ACL_ROUTE_LOAD_SUCCESS';
export const ACL_ROUTE_LOAD_FAIL = 'ACL_ROUTE_LOAD_FAIL';
export const ACL_ROUTE_CLEAR = 'ACL_ROUTE_CLEAR';

export const ACL_ROUTE_CREATE = 'ACL_ROUTE_CREATE';
export const ACL_ROUTE_CREATE_SUCCESS = 'ACL_ROUTE_CREATE_SUCCESS';
export const ACL_ROUTE_CREATE_FAIL = 'ACL_ROUTE_CREATE_FAIL';

export const ACL_ROUTE_UPDATE = 'ACL_ROUTE_UPDATE';
export const ACL_ROUTE_UPDATE_SUCCESS = 'ACL_ROUTE_UPDATE_SUCCESS';
export const ACL_ROUTE_UPDATE_FAIL = 'ACL_ROUTE_UPDATE_FAIL';

export const ACL_ROUTE_DELETE = 'ACL_ROUTE_DELETE';
export const ACL_ROUTE_DELETE_SUCCESS = 'ACL_ROUTE_DELETE_SUCCESS';
export const ACL_ROUTE_DELETE_FAIL = 'ACL_ROUTE_DELETE_FAIL';

export const ACL_ROUTE_CLEAR_NETWORK_STATE = 'ACL_ROUTE_CLEAR_NETWORK_STATE';
